import { createServerClient } from '@/lib/supabase/server';
import { buildCoachSummary, bestWeekday } from '@/lib/coach/aggregate';
import PrintButton from '@/components/dashboard/PrintButton';

export const metadata = { title: 'Year in Review · MV Habits' };

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="flex-1 text-center py-[14px] px-2 border border-[#e3e3e3] rounded-lg">
      <div className="text-[26px] font-extrabold text-[#555555]">{value}</div>
      <div className="text-xs font-semibold tracking-[0.06em] uppercase text-[#888888] mt-1">{label}</div>
    </div>
  );
}

// Printable, light-themed (so the PDF is clean regardless of app theme).
export default async function YearInReviewPage() {
  const supabase = await createServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return <div className="p-10">Please sign in.</div>;

  const summary = await buildCoachSummary(supabase, user.id, 365);

  const partOfDayTop = summary
    ? (Object.entries(summary.partOfDay).sort((a, b) => b[1] - a[1])[0] ?? ['—', 0])
    : ['—', 0];

  return (
    <div className="bg-white text-[#191919] min-h-screen px-5 py-8 font-[system-ui,-apple-system,sans-serif]">
      <style>{`@media print { .no-print { display: none !important; } @page { margin: 16mm; } body { background: #fff; } }`}</style>

      <div className="max-w-[640px] mx-auto">
        <div className="flex justify-between items-start mb-6">
          <div>
            <h1 className="m-0 text-3xl font-extrabold tracking-[-0.02em]">Year in Review</h1>
            <p className="mt-1 text-[13px] text-[#888888]">
              {summary ? `${summary.from} → ${summary.to}` : 'MV Habits'}
            </p>
          </div>
          <div className="no-print flex gap-2 flex-shrink-0">
            <a
              href="/api/export?format=year-csv"
              className="px-4 py-2.5 rounded-[12px] no-underline border border-[#e3e3e3] bg-white text-[#555555] text-[14px] font-bold"
            >
              Download CSV
            </a>
            <PrintButton />
          </div>
        </div>

        {!summary || summary.totalCompletions === 0 ? (
          <p className="text-[15px] text-[#888888] py-10 text-center">
            No habit history to summarize yet. Come back after you&apos;ve logged some habits.
          </p>
        ) : (
          <>
            <div className="flex gap-2.5 mb-6">
              <Stat label="Completions" value={summary.totalCompletions.toLocaleString()} />
              <Stat label="Active days" value={summary.activeDays} />
              <Stat label="Completion" value={`${summary.overallCompletionRate}%`} />
            </div>

            <div className="flex gap-2.5 mb-[28px]">
              <Stat label="Strongest day" value={bestWeekday(summary.weekday) ?? '—'} />
              <Stat label="Best time" value={String(partOfDayTop[0]).replace(/^\w/, (c) => c.toUpperCase())} />
              <Stat label="Habits tracked" value={summary.totalHabits} />
            </div>

            {/* Same definition as the dashboard Overview's "Best Streak" card
                (lib/stats/habitStats.ts) — always matches that number exactly. */}
            <div className="flex gap-2.5 mb-[28px]">
              <Stat label="Best Streak" value={summary.bestStreak} />
              <Stat label="Total Done" value={summary.lifetimeCompletions.toLocaleString()} />
            </div>

            <h2 className="text-lg font-bold m-0 mb-3">By habit</h2>
            <table className="w-full border-collapse text-base">
              <thead>
                <tr className="text-left text-[#888888] text-xs uppercase tracking-[0.05em]">
                  <th className="px-1.5 py-2">Habit</th>
                  <th className="px-1.5 py-2 text-right">Done</th>
                  <th className="px-1.5 py-2 text-right">Rate</th>
                  <th className="px-1.5 py-2 text-right">Best streak</th>
                </tr>
              </thead>
              <tbody>
                {[...summary.habits].sort((a, b) => b.completions - a.completions).map((h, i) => (
                  <tr key={i} className="border-t border-t-[#ececec]">
                    <td className="px-1.5 py-2.5 font-semibold">
                      {h.name} {h.isBad && <span className="text-[#888888] font-normal">(avoid)</span>}
                    </td>
                    <td className="px-1.5 py-2.5 text-right">{h.completions}</td>
                    <td className="px-1.5 py-2.5 text-right">{h.completionRate}%</td>
                    <td className="px-1.5 py-2.5 text-right">{h.longestStreak}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            <p className="mt-[28px] text-xs text-[#adadad] text-center">
              Generated by MV Habits · Use “Save as PDF” or your browser’s print dialog.
            </p>
          </>
        )}
      </div>
    </div>
  );
}
